"""empty message

Revision ID: 4555ea6abf81
Revises: 
Create Date: 2020-12-06 17:57:24.847266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4555ea6abf81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_divisi', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jenis_toppgun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_jenis_toppgun', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategori_lean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_kategori_lean', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategori_wbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_kategori_wbs', sa.String(length=50), nullable=False),
    sa.Column('kategori_wbs', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_kategori_wbs')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('divisi', sa.String(length=30), nullable=True),
    sa.Column('kategori_wbs', sa.String(length=300), nullable=True),
    sa.Column('wbs_spesifik', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wbs_level2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_wbs_level2', sa.String(length=50), nullable=False),
    sa.Column('wbs_level2', sa.String(length=50), nullable=True),
    sa.Column('id_wbs_spesifik', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_wbs_level2')
    )
    op.create_table('wbs_level3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_wbs_level3', sa.String(length=50), nullable=False),
    sa.Column('wbs_level3', sa.String(length=50), nullable=True),
    sa.Column('id_wbs_level2', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_wbs_level3')
    )
    op.create_table('wbs_spesifik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_wbs_spesifik', sa.String(length=50), nullable=False),
    sa.Column('wbs_spesifik', sa.String(length=50), nullable=True),
    sa.Column('id_kategori_wbs', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_wbs_spesifik')
    )
    op.create_table('input_wbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_id_kategori_wbs', sa.String(length=300), nullable=True),
    sa.Column('input_id_wbs_spesifik', sa.String(length=300), nullable=True),
    sa.Column('input_id_wbs_level2', sa.String(length=300), nullable=True),
    sa.Column('input_id_wbs_level3', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['input_id_kategori_wbs'], ['kategori_wbs.id_kategori_wbs'], ),
    sa.ForeignKeyConstraint(['input_id_wbs_level2'], ['wbs_level2.id_wbs_level2'], ),
    sa.ForeignKeyConstraint(['input_id_wbs_level3'], ['wbs_level3.id_wbs_level3'], ),
    sa.ForeignKeyConstraint(['input_id_wbs_spesifik'], ['wbs_spesifik.id_wbs_spesifik'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_wbs_level2', sa.String(length=300), nullable=True),
    sa.Column('post_wbs_level3', sa.String(length=300), nullable=True),
    sa.Column('post_judul', sa.String(length=300), nullable=True),
    sa.Column('post_deskripsi', sa.Text(), nullable=True),
    sa.Column('post_jenis_toppgun', sa.String(length=300), nullable=True),
    sa.Column('post_kategori_lean', sa.String(length=300), nullable=True),
    sa.Column('post_file_url', sa.String(length=300), nullable=True),
    sa.Column('post_wbs_terkait', sa.Text(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('input_wbs')
    op.drop_table('wbs_spesifik')
    op.drop_table('wbs_level3')
    op.drop_table('wbs_level2')
    op.drop_table('user')
    op.drop_table('kategori_wbs')
    op.drop_table('kategori_lean')
    op.drop_table('jenis_toppgun')
    op.drop_table('divisi')
    # ### end Alembic commands ###
