"""empty message

Revision ID: 70572f475f4a
Revises: 
Create Date: 2020-12-13 23:05:06.647086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70572f475f4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'kategori_wbs', ['post_kategori_wbs'], ['id_kategori_wbs'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
