"""empty message

Revision ID: 938cf7b9f718
Revises: 70572f475f4a
Create Date: 2020-12-13 23:10:29.670667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938cf7b9f718'
down_revision = '70572f475f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'wbs_spesifik', ['post_wbs_spesifik'], ['id_wbs_spesifik'])
    op.create_foreign_key(None, 'post', 'wbs_level2', ['post_wbs_level2'], ['id_wbs_level2'])
    op.create_foreign_key(None, 'post', 'wbs_level3', ['post_wbs_level3'], ['id_wbs_level3'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
