"""empty message

Revision ID: ff401d76beec
Revises: 
Create Date: 2020-12-12 15:14:31.835579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff401d76beec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divisi', sa.Column('id_divisi', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'divisi', ['id_divisi'])
    op.add_column('jenis_toppgun', sa.Column('id_jenis_toppgun', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'jenis_toppgun', ['id_jenis_toppgun'])
    op.add_column('kategori_lean', sa.Column('id_kategori_lean', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'kategori_lean', ['id_kategori_lean'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kategori_lean', type_='unique')
    op.drop_column('kategori_lean', 'id_kategori_lean')
    op.drop_constraint(None, 'jenis_toppgun', type_='unique')
    op.drop_column('jenis_toppgun', 'id_jenis_toppgun')
    op.drop_constraint(None, 'divisi', type_='unique')
    op.drop_column('divisi', 'id_divisi')
    # ### end Alembic commands ###
